name: demo-uat

replicaCount: 1

image:
  registry: docker.io
  repository: ops2dev/demo11
  tag: "1.0"

containerPort: 80

envVarName: demo-uat

state: uat
color: yellow

service:
  port: 80
  nodePort: 30081
