name: demo-prd
namespace: prd

replicaCount: 1

image:
  repository: ops2dev/demo11
  tag: 1.0

containerPort: 80

envVarName: demo-prd

state: prd
color: green

service:
  port: 80
  nodePort: 30082
